### ISSUE TITLE
CI: "Build & Test (wasm32-wasi via wasmtime)" reports green while building and running nothing

### ISSUE THREAD

**Issue by cataggar** [cataggar/wamr#935]
## Summary

The `wasi-test` job (`Build & Test (wasm32-wasi via wasmtime)`) passes on every PR, but it has not actually built or executed anything since it was introduced. Both of its meaningful steps are configured so that failure cannot fail the job.

This was found incidentally while checking whether an unrelated wasm build failure was pre-existing.

## Evidence

`.github/workflows/ci.yml:117-125`:

```yaml
      - name: Build for wasm32-wasi
        continue-on-error: true                                    # <-- build failure ignored
        run: zig build -Doptimize=ReleaseSafe -Dtarget=wasm32-wasi -Dstrip=true

      - name: Run wamr via wasmtime
        run: |
          wasmtime --version
          # Smoke test: run the wasm binary with --help or similar
          wasmtime zig-out/bin/wamr.wasm -- --version || echo "wamr.wasm executed (exit code: $?)"
                                                     # ^-- run failure ignored
```

The build step fails, `continue-on-error: true` swallows it. The run step then invokes `wasmtime` on `zig-out/bin/wamr.wasm`, which was never produced; `|| echo` swallows that too. The job reports **pass**.

From the CI log of a recent unrelated PR (#934, run `31412043756`, job `93532188206`), which reported ✅:

```
Build for wasm32-wasi   <zig>/lib/std/c.zig:10660:12: error: dependency on libc must be explicitly specified in the build command
Build for wasm32-wasi   src/platform/parking_lot.zig:122:25: error: expected 32-bit integer type or smaller; found 64-bit integer type
Build for wasm32-wasi   src/platform/platform.zig:168:39: error: type 'void' does not support array initialization syntax
...
Run wamr via wasmtime   wamr.wasm executed (exit code: 1)
```

`exit code: 1` is `wasmtime` failing to open a binary that does not exist. That message is worded as if it were a success.

Introduced in bf7ab7ef (2026-07-13, #900). `git blame` confirms `continue-on-error: true` has been on this step since the job landed, so this check has never had teeth.

## Impact

Two separate costs:

1. The repo advertises a `wasm32-wasi` build gate that does not exist. The actual state of that target is tracked in a companion issue — it is broken with ~16 distinct compile errors, most of them in our own source.
2. It is actively misleading during review. A green `Build & Test (wasm32-wasi via wasmtime)` on a PR is currently evidence of nothing, and anyone reasoning about whether their change affected the wasm target will draw the wrong conclusion.

## Suggested fix

Fix the underlying build first, then make the gate real:

- Drop `continue-on-error: true` from the build step.
- Replace `|| echo "wamr.wasm executed (exit code: $?)"` with an assertion that the binary exists and that the run exits as expected.

If `wasm32-wasi` is not intended to be a supported target right now, the honest alternative is to delete the job rather than leave a permanently-green placeholder. A third option, if the target is aspirational, is to keep the job but mark it as expected-to-fail in a way that is visible (e.g. a scheduled-only job), so it does not sit in the required-checks list looking like coverage.

Note also that `|| echo "... (exit code: $?)"` does not do what it appears to do even when the binary exists: `$?` inside the `echo` is evaluated after `||` and does not reliably report the failing command's status.
